package github.io.monthalcantara.desafiomaxxi.exceptions;

public class RecursoNaoEncontrado extends RuntimeException {
    public RecursoNaoEncontrado(String message) {
        super(message);
    }
}
